### ISSUE TITLE
Make errors more explicit

### ISSUE THREAD

**Issue by bmicklea** [jozu-ai/kitops#510] opened 2024-10-04 17:56 UTC
**Describe the problem you're trying to solve**
When trying to `kit push` a ModelKit to a repository that doesn't exist you get a very general (and not super helpful) error:
>  [ERROR] Failed to push: failed to copy to remote: HEAD : response status code 401: Unauthorized

**Describe the solution you'd like**
We can't know what exactly the error was, but we can make the message more suggestive. Something like:
>  [ERROR] Failed to push: failed to copy to remote: HEAD : response status code 401: Unauthorized. Check that the organizaiton and repository you're pushing to exists and that you have write permissions.

**Additional context**
This is primarily about helping with the user experience when there are errors, remembering that some KitOps users won't be experienced software developers.

**Comment by TusharMohapatra07** [comment] 2024-10-04 18:53
I would like to work on this issue.

**Comment by nitesh2920** [comment] 2024-10-05 10:48
If this issueis still open can I work on it @bmicklea

**Comment by Jwilliamsr** [comment] 2024-10-07 15:15
@nitesh2920 the issue is still open, however, @TusharMohapatra07 already requested to work on it. Feel free to checkout our other #491 Hacktoberfest issues

**Comment by RS-labhub** [comment] 2024-10-09 09:07
Close this issue.. 🥺

**Closed** 2024-10-09 11:15 UTC
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted
